const palette = {
  blue: '#2F6BFF',
  blueLight: '#68A4FF',
  teal: '#13B8A6',
  violet: '#7567FF',
  amber: '#F5B84B',
  ink: '#101621',

  light: {
    background: '#F5F7FB',
    surface: '#FFFFFF',
    surfaceHighlight: '#EEF3FA',
    surfaceRaised: '#FBFCFF',
    textPrimary: '#101621',
    textSecondary: '#485465',
    textMuted: '#7A8798',
    textInverse: '#FFFFFF',
    border: '#D9E1EC',
    borderStrong: '#C5D0DE',
  },

  dark: {
    background: '#0B1017',
    surface: '#121923',
    surfaceHighlight: '#1A2431',
    surfaceRaised: '#151F2B',
    textPrimary: '#F7FAFF',
    textSecondary: '#B9C6D8',
    textMuted: '#7E8DA3',
    textInverse: '#FFFFFF',
    border: '#263548',
    borderStrong: '#33465F',
  },

  status: {
    success: '#16A34A',
    warning: '#F59E0B',
    error: '#DC2626',
    info: '#2563EB',
  },
};

export const lightTheme = {
  dark: false,
  colors: {
    background: palette.light.background,
    surface: palette.light.surface,
    surfaceHighlight: palette.light.surfaceHighlight,
    surfaceRaised: palette.light.surfaceRaised,
    primary: palette.blue,
    primaryStrong: '#1F55E8',
    secondary: '#324052',
    accent: palette.teal,
    violet: palette.violet,
    amber: palette.amber,
    panel: 'rgba(255,255,255,0.88)',
    panelStrong: '#FFFFFF',
    overlay: 'rgba(9, 15, 26, 0.62)',
    backdrop: {
      base: '#F5F7FB',
      glowA: 'rgba(47,107,255,0.16)',
      glowB: 'rgba(19,184,166,0.13)',
      glowC: 'rgba(245,184,75,0.13)',
      grid: 'rgba(16,22,33,0.08)',
    },
    text: {
      primary: palette.light.textPrimary,
      secondary: palette.light.textSecondary,
      muted: palette.light.textMuted,
      inverse: palette.light.textInverse,
    },
    status: palette.status,
    border: palette.light.border,
    borderStrong: palette.light.borderStrong,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 28,
    full: 9999,
  },
  typography: {
    display: { fontSize: 34, lineHeight: 40, fontWeight: '900' },
    header: { fontSize: 26, lineHeight: 32, fontWeight: '900', letterSpacing: 0 },
    title: { fontSize: 22, lineHeight: 28, fontWeight: '800', letterSpacing: 0 },
    subHeader: { fontSize: 18, lineHeight: 24, fontWeight: '800', letterSpacing: 0 },
    section: { fontSize: 16, lineHeight: 22, fontWeight: '800', letterSpacing: 0 },
    body: { fontSize: 14, lineHeight: 20, fontWeight: '500', letterSpacing: 0 },
    label: { fontSize: 12, lineHeight: 16, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0 },
    caption: { fontSize: 12, lineHeight: 17, fontWeight: '600', letterSpacing: 0 },
  },
  shadows: {
    card: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.07,
      shadowRadius: 30,
      elevation: 3,
    },
    floating: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.13,
      shadowRadius: 38,
      elevation: 8,
    },
    focus: {
      shadowColor: palette.blue,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.22,
      shadowRadius: 18,
      elevation: 4,
    },
  },
};

export const darkTheme = {
  ...lightTheme,
  dark: true,
  colors: {
    ...lightTheme.colors,
    background: palette.dark.background,
    surface: palette.dark.surface,
    surfaceHighlight: palette.dark.surfaceHighlight,
    surfaceRaised: palette.dark.surfaceRaised,
    primary: '#6EA8FF',
    primaryStrong: '#4F83F1',
    secondary: '#A4ADBA',
    accent: '#35C7B6',
    violet: '#9D91FF',
    amber: '#FFD17A',
    panel: 'rgba(17,24,33,0.82)',
    panelStrong: '#111821',
    overlay: 'rgba(2, 6, 13, 0.74)',
    backdrop: {
      base: '#080C12',
      glowA: 'rgba(47,107,255,0.22)',
      glowB: 'rgba(18,184,166,0.16)',
      glowC: 'rgba(245,184,75,0.10)',
      grid: 'rgba(247,250,255,0.07)',
    },
    text: {
      primary: palette.dark.textPrimary,
      secondary: palette.dark.textSecondary,
      muted: palette.dark.textMuted,
      inverse: '#FFFFFF',
    },
    border: palette.dark.border,
    borderStrong: palette.dark.borderStrong,
  },
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.28,
      shadowRadius: 30,
      elevation: 4,
    },
    floating: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.42,
      shadowRadius: 34,
      elevation: 8,
    },
    focus: {
      shadowColor: '#6EA8FF',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.32,
      shadowRadius: 20,
      elevation: 5,
    },
  }
};

export type Theme = typeof lightTheme;
// Default export for backward compatibility relative to user instructions
export const theme = lightTheme; 
