const palette = {
  blue: '#3b82f6',
  blueLight: '#60a5fa',
  blueSubtle: '#dbeafe',
  teal: '#14b8a6',
  tealSubtle: '#ccfbf1',
  violet: '#6366f1',
  amber: '#f59e0b',
  amberSubtle: '#fef3c7',
  ink: '#0f172a',
  rose: '#f43f5e',
  emerald: '#10b981',
  orange: '#f97316',
  cyan: '#06b6d4',
  slate: '#64748b',

  light: {
    background: '#f8fafc',
    surface: 'rgba(255, 255, 255, 0.72)',
    surfaceHighlight: '#f1f5f9',
    surfaceRaised: '#ffffff',
    glassBg: 'rgba(255, 255, 255, 0.55)',
    glassBorder: 'rgba(255, 255, 255, 0.45)',
    textPrimary: '#0f172a',
    textSecondary: '#475569',
    textMuted: '#94a3b8',
    textInverse: '#ffffff',
    border: 'rgba(226, 232, 240, 0.65)',
    borderStrong: '#cbd5e1',
    skeletonBase: '#e2e8f0',
    skeletonShimmer: '#f1f5f9',
  },

  dark: {
    background: '#090a0f',
    surface: 'rgba(15, 23, 42, 0.65)',
    surfaceHighlight: '#1e293b',
    surfaceRaised: '#1e293b',
    glassBg: 'rgba(15, 23, 42, 0.55)',
    glassBorder: 'rgba(255, 255, 255, 0.08)',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#64748b',
    textInverse: '#ffffff',
    border: 'rgba(30, 41, 59, 0.65)',
    borderStrong: '#334155',
    skeletonBase: '#1e293b',
    skeletonShimmer: '#334155',
  },

  status: {
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
  },
};

export const lightTheme = {
  dark: false,
  colors: {
    background: palette.light.background,
    surface: palette.light.surface,
    surfaceHighlight: palette.light.surfaceHighlight,
    surfaceRaised: palette.light.surfaceRaised,
    primary: palette.blue,
    primaryStrong: '#2563eb',
    secondary: '#1e293b',
    accent: palette.teal,
    violet: palette.violet,
    amber: palette.amber,
    panel: 'rgba(255,255,255,0.75)',
    panelStrong: '#ffffff',
    overlay: 'rgba(15, 23, 42, 0.45)',
    backdrop: {
      base: palette.light.background,
      glowA: 'rgba(59,130,246,0.18)',
      glowB: 'rgba(20,184,166,0.15)',
      glowC: 'rgba(245,158,11,0.12)',
      grid: 'rgba(15,23,42,0.04)',
    },
    text: {
      primary: palette.light.textPrimary,
      secondary: palette.light.textSecondary,
      muted: palette.light.textMuted,
      inverse: palette.light.textInverse,
    },
    status: palette.status,
    border: palette.light.border,
    borderStrong: palette.light.borderStrong,
  },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
  borderRadius: { sm: 6, md: 8, lg: 8, xl: 8, xxl: 8, full: 9999 },
  typography: {
    display: { fontSize: 38, lineHeight: 46, fontWeight: '900', letterSpacing: 0 },
    header: { fontSize: 30, lineHeight: 36, fontWeight: '800', letterSpacing: 0 },
    title: { fontSize: 24, lineHeight: 30, fontWeight: '700', letterSpacing: 0 },
    subHeader: { fontSize: 20, lineHeight: 26, fontWeight: '700', letterSpacing: 0 },
    section: { fontSize: 16, lineHeight: 24, fontWeight: '600', letterSpacing: 0 },
    body: { fontSize: 15, lineHeight: 24, fontWeight: '400', letterSpacing: 0.1 },
    label: { fontSize: 13, lineHeight: 18, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.8 },
    caption: { fontSize: 13, lineHeight: 18, fontWeight: '500', letterSpacing: 0.2 },
  },
  shadows: {
    card: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.04,
      shadowRadius: 18,
      elevation: 3,
    },
    floating: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.08,
      shadowRadius: 36,
      elevation: 8,
    },
    focus: {
      shadowColor: palette.blue,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
  },
};

export const darkTheme = {
  ...lightTheme,
  dark: true,
  colors: {
    ...lightTheme.colors,
    background: palette.dark.background,
    surface: palette.dark.surface,
    surfaceHighlight: palette.dark.surfaceHighlight,
    surfaceRaised: palette.dark.surfaceRaised,
    primary: '#3b82f6',
    primaryStrong: '#60a5fa',
    secondary: '#94a3b8',
    accent: '#2dd4bf',
    violet: '#818cf8',
    amber: '#fbbf24',
    panel: 'rgba(15, 23, 42, 0.7)',
    panelStrong: '#0f172a',
    overlay: 'rgba(5, 8, 12, 0.65)',
    backdrop: {
      base: palette.dark.background,
      glowA: 'rgba(59,130,246,0.15)',
      glowB: 'rgba(45,212,191,0.12)',
      glowC: 'rgba(251,191,36,0.08)',
      grid: 'rgba(255,255,255,0.02)',
    },
    text: {
      primary: palette.dark.textPrimary,
      secondary: palette.dark.textSecondary,
      muted: palette.dark.textMuted,
      inverse: '#ffffff',
    },
    border: palette.dark.border,
    borderStrong: palette.dark.borderStrong,
  },
  shadows: {
    card: {shadowColor: '#000',shadowOffset: { width: 0, height: 8 },shadowOpacity: 0.35,shadowRadius: 24,elevation: 4},
    floating: {shadowColor: '#000',shadowOffset: { width: 0, height: 20 },shadowOpacity: 0.45,shadowRadius: 42,elevation: 8},
    focus: {shadowColor: '#3b82f6',shadowOffset: { width: 0, height: 0 },shadowOpacity: 0.25,shadowRadius: 16,elevation: 5},
  }
};

export type Theme = typeof lightTheme;
export const theme = lightTheme;
