const palette = {
  blue: '#2563eb',
  blueLight: '#4f83ff',
  blueSubtle: '#eaf1ff',
  teal: '#0ea5a6',
  tealSubtle: '#e6f8f7',
  violet: '#4f46e5',
  amber: '#d97706',
  amberSubtle: '#fff7e6',
  ink: '#111827',
  rose: '#e11d48',
  emerald: '#16a66a',
  orange: '#ea580c',
  cyan: '#0891b2',
  slate: '#64748b',

  light: {
    background: '#f5f7fb',
    surface: 'rgba(255, 255, 255, 0.94)',
    surfaceHighlight: '#f0f3f8',
    surfaceRaised: '#ffffff',
    glassBg: 'rgba(255, 255, 255, 0.88)',
    glassBorder: 'rgba(202, 211, 225, 0.7)',
    textPrimary: '#111827',
    textSecondary: '#4b5870',
    textMuted: '#8390a5',
    textInverse: '#ffffff',
    border: '#dfe5ef',
    borderStrong: '#c8d1df',
    skeletonBase: '#e5eaf2',
    skeletonShimmer: '#f4f6fa',
  },

  dark: {
    background: '#080d16',
    surface: 'rgba(15, 24, 38, 0.94)',
    surfaceHighlight: '#172235',
    surfaceRaised: '#111b2b',
    glassBg: 'rgba(15, 24, 38, 0.9)',
    glassBorder: '#26354a',
    textPrimary: '#f4f7fb',
    textSecondary: '#b2bfd0',
    textMuted: '#718097',
    textInverse: '#ffffff',
    border: '#26354a',
    borderStrong: '#3a4b63',
    skeletonBase: '#172235',
    skeletonShimmer: '#223149',
  },

  status: {
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
  },
};

export const lightTheme = {
  dark: false,
  colors: {
    background: palette.light.background,
    surface: palette.light.surface,
    surfaceHighlight: palette.light.surfaceHighlight,
    surfaceRaised: palette.light.surfaceRaised,
    primary: palette.blue,
    primaryStrong: '#1d4ed8',
    secondary: '#182235',
    accent: palette.teal,
    violet: palette.violet,
    amber: palette.amber,
    panel: '#ffffff',
    panelStrong: '#ffffff',
    overlay: 'rgba(15, 23, 42, 0.45)',
    backdrop: {
      base: palette.light.background,
      glowA: 'rgba(37,99,235,0.07)',
      glowB: 'rgba(14,165,166,0.05)',
      glowC: 'rgba(217,119,6,0.04)',
      grid: 'rgba(17,24,39,0.035)',
    },
    text: {
      primary: palette.light.textPrimary,
      secondary: palette.light.textSecondary,
      muted: palette.light.textMuted,
      inverse: palette.light.textInverse,
    },
    status: palette.status,
    border: palette.light.border,
    borderStrong: palette.light.borderStrong,
  },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
  borderRadius: { sm: 4, md: 6, lg: 8, xl: 8, xxl: 8, full: 9999 },
  typography: {
    display: { fontSize: 38, lineHeight: 46, fontWeight: '800', letterSpacing: 0 },
    header: { fontSize: 30, lineHeight: 36, fontWeight: '800', letterSpacing: 0 },
    title: { fontSize: 24, lineHeight: 30, fontWeight: '800', letterSpacing: 0 },
    subHeader: { fontSize: 20, lineHeight: 26, fontWeight: '700', letterSpacing: 0 },
    section: { fontSize: 16, lineHeight: 24, fontWeight: '600', letterSpacing: 0 },
    body: { fontSize: 15, lineHeight: 24, fontWeight: '400', letterSpacing: 0.1 },
    label: { fontSize: 13, lineHeight: 18, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.8 },
    caption: { fontSize: 13, lineHeight: 18, fontWeight: '500', letterSpacing: 0.2 },
  },
  shadows: {
    card: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.045,
      shadowRadius: 14,
      elevation: 2,
    },
    floating: {
      shadowColor: '#0f172a',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.1,
      shadowRadius: 28,
      elevation: 6,
    },
    focus: {
      shadowColor: palette.blue,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
    },
  },
};

export const darkTheme = {
  ...lightTheme,
  dark: true,
  colors: {
    ...lightTheme.colors,
    background: palette.dark.background,
    surface: palette.dark.surface,
    surfaceHighlight: palette.dark.surfaceHighlight,
    surfaceRaised: palette.dark.surfaceRaised,
    primary: '#4f83ff',
    primaryStrong: '#75a0ff',
    secondary: '#94a3b8',
    accent: '#2cc7c5',
    violet: '#818cf8',
    amber: '#fbbf24',
    panel: 'rgba(15, 23, 42, 0.7)',
    panelStrong: '#0f172a',
    overlay: 'rgba(5, 8, 12, 0.65)',
    backdrop: {
      base: palette.dark.background,
      glowA: 'rgba(79,131,255,0.1)',
      glowB: 'rgba(44,199,197,0.07)',
      glowC: 'rgba(251,191,36,0.04)',
      grid: 'rgba(255,255,255,0.025)',
    },
    text: {
      primary: palette.dark.textPrimary,
      secondary: palette.dark.textSecondary,
      muted: palette.dark.textMuted,
      inverse: '#ffffff',
    },
    border: palette.dark.border,
    borderStrong: palette.dark.borderStrong,
  },
  shadows: {
    card: {shadowColor: '#000',shadowOffset: { width: 0, height: 8 },shadowOpacity: 0.35,shadowRadius: 24,elevation: 4},
    floating: {shadowColor: '#000',shadowOffset: { width: 0, height: 20 },shadowOpacity: 0.45,shadowRadius: 42,elevation: 8},
    focus: {shadowColor: '#3b82f6',shadowOffset: { width: 0, height: 0 },shadowOpacity: 0.25,shadowRadius: 16,elevation: 5},
  }
};

export type Theme = typeof lightTheme;
export const theme = lightTheme;
